version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Dependencies"
    target-branch: "2.6.x"
    groups:
      phpstan:
        patterns:
          - "phpstan/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "CI"
    target-branch: "2.6.x"
    groups:
      doctrine:
        patterns:
          - "doctrine/*"
