
name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  coding-standards:
    name: "Coding Standards"
    uses: "greg0ire/doctrine-dot-github/.github/workflows/coding-standards.yml@dev-file"
