name: "Composer Lint"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - "composer.json"
  push:
    branches:
      - "*.x"
    paths:
      - "composer.json"

jobs:
  composer-lint:
    name: "Composer Lint"
    uses: "greg0ire/.github/.github/workflows/composer-lint.yml@maintenance"
    with:
      php-version: "8.1"
