

name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  phpunit:
    name: "PHPUnit"
    uses: "greg0ire/doctrine-dot-github/.github/workflows/continuous-integration.yml@fix-comparison"
    with:
      php-versions: '["8.1", "8.2", "8.3", "8.4", "8.5"]'
    secrets:
      CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
