name: "Documentation"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - .github/workflows/documentation.yml
      - docs/**
  push:
    branches:
      - "*.x"
    paths:
      - .github/workflows/documentation.yml
      - docs/**

jobs:
  documentation:
    name: "Documentation"
    uses: "greg0ire/.github/.github/workflows/documentation.yml@maintenance"
