
name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
  push:
    branches:
      - "*.x"

jobs:
  static-analysis:
    name: "Static Analysis"
    uses: "greg0ire/.github/.github/workflows/static-analysis.yml@maintenance"
    with:
      php-version: "8.1"
